const fs = require("fs");
const path = require("path");

const keensDir = path.join(__dirname, "src/assets/Keens");
const outputFile = path.join(__dirname, "src/shared/constant/AppResource.js");

// Bỏ qua các file SVG có ký tự đặc biệt không hợp lệ trong tên file (ví dụ: #)
function getAllSvgFiles(dir, group) {
    const files = fs.readdirSync(dir);
    return files
        .filter((f) => f.endsWith(".svg") && !f.includes("#")) // Bỏ qua file có ký tự #
        .map((f) => {
            // Loại bỏ khoảng trắng và ký tự đặc biệt trong tên biến import
            const importName = `${group}${f.replace(/[^a-zA-Z0-9_]/g, "_")}`;
            // Key object: thay thế khoảng trắng và ký tự đặc biệt bằng _
            const key = f.replace(/\.svg$/, "").replace(/[^a-zA-Z0-9_]/g, "_");
            return {
                importName,
                relPath: `../../assets/Keens/${group}/${f}`,
                key,
            };
        });
}

const groups = fs.readdirSync(keensDir).filter((f) => fs.statSync(path.join(keensDir, f)).isDirectory());

let importLines = [];
let objectLines = [];

groups.forEach((group) => {
    const files = getAllSvgFiles(path.join(keensDir, group), group);
    if (files.length === 0) return;
    importLines.push(`// ${group}`);
    files.forEach(({ importName, relPath }) => {
        importLines.push(`import ${importName} from "${relPath}";`);
    });
    objectLines.push(`    ${group}: {`);
    files.forEach(({ importName, key }) => {
        objectLines.push(`      "${key}": ${importName},`);
    });
    objectLines.push("    },");
});

const content = `// Auto-generated by generateAppResource.js
${importLines.join("\n")}

const AppResource = {
  keens: {
${objectLines.join("\n")}
  }
};

export default AppResource;
`;

fs.writeFileSync(outputFile, content);
console.log("AppResource.js generated!");

// Đổi sang CommonJS để dùng require thay vì import (vì project đang để type: module)
// Đổi tên file này thành generateAppResource.cjs để chạy được với require
